version: '3.8'

services:
  app:
    container_name: muslimly_backend
    build: .
    restart: always
    # Ports removed, accessed via Nginx
    expose:
      - "8080"
    environment:
      - CONFIG_FILE=/app/config.yaml
      - DB_HOST=muslimly_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TZ=Asia/Jakarta
    volumes:
      - ./config.yaml:/root/config.yaml
      - ./firebase-service-account.json:/root/firebase-service-account.json
    depends_on:
      - db
    networks:
      - muslimly_net

  db:
    container_name: muslimly_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Jakarta
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - muslimly_net

  nginx:
    image: nginx:alpine
    container_name: muslimly_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - muslimly_net

  certbot:
    image: certbot/certbot
    container_name: muslimly_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  muslimly_net:
    driver: bridge

volumes:
  postgres_data:

